# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn build
      - run:
          name: boot dummy server
          command: yarn start:test-server
          background: true
      - run: yarn test
      - run: sh packages/arlecchino-cli/scripts/e2e.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
#     - run: yarn lint

  deploy:
    docker:
      - image: node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "yarn.lock" }}
            - npm-cache
      - run: yarn install --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn build
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - run:
          name: Publish
          command: |
            yarn publish:npm

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
